image: eclipse-temurin:17

stages:
  - build
  - deploy

before_script:
  - chmod a+x ./gradlew
  - chmod 770 gradlew

build:
  stage: build
  script:
    - ./gradlew build -PmcVer="${MC_VER}" -PinfoGitCommit="${CI_COMMIT_SHA}" -PinfoGitBranch="${CI_COMMIT_BRANCH}" -PinfoBuildSource="GitLab CI (${CI_PIPELINE_ID})" --gradle-user-home cache/;
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/libs
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

deploy:
  stage: build
  script:
    - mkdir libs
#    - git remote set-url origin https://gitlab.zendovo.eu/netleak/safespawn
#    - ./gradlew clean build makeChangelog publish curseforgeXXXXX -S -i --refresh-dependencies
    # Export all variables, uncomment if you want a list of all variables at the end of the job
    # - export
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/libs
  artifacts:
    paths:
      - build/libs/*.jar
      - output/*.jar
      - output/*.html
    expire_in: 1 week