image: eclipse-temurin:17

stages:
  - build

.build_java:
  cache:
    key: "gradleCache"
    policy: pull-push
    paths:
      - .gradle
      - cache/
  allow_failure: true
  before_script:
    - chmod +x ./gradlew

build:
  stage: build
  parallel:
    matrix:
      - MC_VER: ["1.20.1"]
  script:
    - ./gradlew clean -PmcVer="${MC_VER}" -PinfoGitCommit="${CI_COMMIT_SHA}" -PinfoGitBranch="${CI_COMMIT_BRANCH}" -PinfoBuildSource="GitLab CI (${CI_PIPELINE_ID})" --gradle-user-home cache/;
    - ./gradlew build -PmcVer="${MC_VER}" -PinfoGitCommit="${CI_COMMIT_SHA}" -PinfoGitBranch="${CI_COMMIT_BRANCH}" -PinfoBuildSource="GitLab CI (${CI_PIPELINE_ID})" --gradle-user-home cache/;
    - ./gradlew mergeJars -PmcVer="${MC_VER}" -PinfoGitCommit="${CI_COMMIT_SHA}" -PinfoGitBranch="${CI_COMMIT_BRANCH}" -PinfoBuildSource="GitLab CI (${CI_PIPELINE_ID})" --gradle-user-home cache/;
  artifacts:
    name: "NightlyBuild_${MC_VER}-${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_TIMESTAMP}"
    paths:
      - build/libs/*.jar
    exclude:
      - build/libs/*-all.jar
      - build/libs/*-dev.jar
      - build/libs/*-sources.jar
    expire_in: 14 days
    when: always
  extends: .build_java