name: CI

on:
  push:
    branches:
      - master
      - main
      - develop
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:21
    env:
      GRADLE_USER_HOME: cache/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Nastavení spustitelných práv pro gradlew
        run: |
          chmod a+x ./gradlew
          chmod 770 gradlew

      - name: Cache Gradle složek
        uses: actions/cache@v4
        with:
          path: |
            .gradle
            cache/
          key: gradleCache-${{ runner.os }}-${{ hashFiles('/.gradle', '/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build projektu
        run: |
          ./gradlew clean -PinfoGitCommit=${GITHUB_SHA} -PinfoGitBranch=${GITHUB_REF} -PinfoBuildSource="GitHub Actions ($GITHUB_RUN_ID)"
          ./gradlew build -PinfoGitCommit=${GITHUB_SHA} -PinfoGitBranch=${GITHUB_REF} -PinfoBuildSource="GitHub Actions ($GITHUB_RUN_ID)"

      - name: Upload build artefaktů
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            fabric/build/libs/*.jar
            forge/build/libs/*.jar
            neoforge/build/libs/*.jar
            !**/build/libs/*-sources.jar
            !**/build/libs/*-javadoc.jar

  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    container:
      image: gradle:8.8.0-jdk17-jammy
    needs: build
    # Spouští se pro pull requesty nebo pro hlavní větve
    if: github.event_name == 'pull_request' || startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/develop')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Sonar scanner
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.temp }}/sonar/cache
            sonar-scanner/
          key: sonar-cache-${{ github.ref_name }}

      - name: Spuštění SonarQube analýzy
        run: gradle sonar
        continue-on-error: true

  release:
    name: Vytvoření releasu
    runs-on: ubuntu-latest
    needs: build
    # Tento job se spustí pouze při pushnutí tagu
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stažení build artefaktů
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Vytvoření GitHub releasu
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files:
            - fabric/build/libs/*.jar
            - forge/build/libs/*.jar
            - neoforge/build/libs/*.jar