name: CI

on:
  push:
    branches:
      - master
      - main
      - develop
    tags:
      - '*'
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:21
    env:
      GRADLE_USER_HOME: cache/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Nastavení spustitelných práv pro gradlew
        run: |
          chmod a+x ./gradlew
          chmod 770 gradlew

      - name: Cache Gradle složek
        uses: actions/cache@v4
        with:
          path: |
            .gradle
            cache/
          key: gradleCache-${{ runner.os }}-${{ hashFiles('/.gradle', '/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build projektu
        run: |
          ./gradlew clean -PinfoGitCommit=${GITHUB_SHA} -PinfoGitBranch=${GITHUB_REF} -PinfoBuildSource="GitHub Actions ($GITHUB_RUN_ID)"
          ./gradlew build -PinfoGitCommit=${GITHUB_SHA} -PinfoGitBranch=${GITHUB_REF} -PinfoBuildSource="GitHub Actions ($GITHUB_RUN_ID)"

      - name: Upload build artefaktů
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            fabric/build/libs/*.jar
            forge/build/libs/*.jar
            neoforge/build/libs/*.jar
            !**/build/libs/*-sources.jar
            !**/build/libs/*-javadoc.jar

  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    container:
      image: gradle:8.12-jdk21
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Nastavení spustitelných práv pro gradlew
        run: |
          chmod a+x ./gradlew
          chmod 770 gradlew
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew build sonar --info

  release:
    name: Vytvoření releasu
    runs-on: ubuntu-latest
    needs: build
    # Tento job se spustí pouze při pushnutí tagu
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stažení build artefaktů
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Vytvoření GitHub releasu
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            fabric/build/libs/*.jar
            forge/build/libs/*.jar
            neoforge/build/libs/*.jar
